### ISSUE TITLE
12.1-2 mistakes between heap and min-heap

### ISSUE THREAD

**Issue by Minys233** [walkccc/CLRS#103]
The problem states *difference between the binary-search-tree property and the **min-heap** property*. The answer is based on the property of **max-heap** where parents are greater equal than children. 
But it should be answered by the property of min-heap, where parents are less equal to children.

**Comment by walkccc** [comment]
Thank you! I've updated the solution [here](https://walkccc.github.io/CLRS/Chap12/12.1/#121-2). Please check it!
