### ISSUE TITLE
15.4-5

### ISSUE THREAD

**Issue by eou** [walkccc/CLRS#108]
PRINT-LCS(c, X, Y)
For 12 line: else if c[i - 1, j] ≥ c[i, j - 1]
missing a statement for else if branch.

It should be:
`else if c[i - 1, j] ≥ c[i, j - 1]
i = i - 1
`

**Comment by walkccc** [comment]
Thank you. I've updated it [here](https://walkccc.github.io/CLRS/Chap15/15.4/#154-5).
