### ISSUE TITLE
22.2-8 Letters go wrong

### ISSUE THREAD

**Issue by lvyougang** [walkccc/CLRS#109]
d(a,b)+2d(s,c)=d(s,a)+d(s,b)<d(s.x)+d(s.b)
d(x,b)=d(s.x)+d(s.b)√
d(x,b)=d(s,c)+d(s,b)×
The author may have mistyped this detail by accident, but I really appreciate the information provided by the author, which has brought great help to my study.

**Comment by walkccc** [comment]
Thank you! I've updated it [here](https://walkccc.github.io/CLRS/Chap22/22.2/#222-8-star).
