### ISSUE TITLE
Problem 22.3-7 in CLRS

### ISSUE THREAD

**Issue by EvgenyMakarov** [walkccc/CLRS#111]
Dear Jay,

I was looking at the solution to problem CLRS on https://walkccc.github.io/CLRS/Chap22/22.3, and it says: "See the algorithm DFS-STACK(G)". However, I couldn't find the DFS-STACK algorithm anywhere on the page. Where is it located?

Sincerely,
Evgeny Makarov

**Comment by walkccc** [comment]
Hi EvgenyMakarov,

Sorry for replying late. I've updated the answer [here](https://walkccc.github.io/CLRS/Chap22/22.3/#223-7).

Please check.
