### ISSUE TITLE
Rendering issue for not equals

### ISSUE THREAD

**Issue by robertmartin8** [walkccc/CLRS#118]
Firstly, this is a very helpful project – thank you!

One minor issue is that there seems to be an issue with the rendering of "not equals":

<img width="526" alt="Screen Shot 2019-05-31 at 10 52 26" src="https://user-images.githubusercontent.com/11792905/58697993-4ce43980-8392-11e9-848e-63c0846aa1c3.png">

I am on the latest Chrome – Version 74.0.3729.169 (Official Build) (64-bit).
I tried on Safari as well, it looks a bit off but not as bad as chrome

Robert

**Comment by walkccc** [comment]
Thanks for reporting the bug. It is fixed now! Please check it.
