### ISSUE TITLE
is problem 4.4.3 wrong?

### ISSUE THREAD

**Issue by JackXuXin** [walkccc/CLRS#119]
> 4.4-3 Use a recursion tree to determine a good asymptotic upper bound on the recurrence T(n) = 4T(n/2+ 2) + n. Use the substitution method to verify your answer

when n = 4, get T(4) = 4T(4/2 + 2) + 4 = 4T(4) + 4 which is endless loop.

**Comment by CurieLuo** [comment]
this problem assumes that T(n)=O(1) for n smaller than some constant.

**Comment by walkccc** [comment]
@CurieLuo is right. Feel free to reopen the issue.
