### ISSUE TITLE
there are several error about latex syntax

### ISSUE THREAD

**Issue by hanleilei** [walkccc/CLRS#121]
Hello Jay,

there are several errors in this way:

"ParseError: KaTeX parse error: Expected '}', got '&' at position 51: …= \\{f(n): &̲ \text{ there e…
"

I'm not latex guru, Could you share me more info about it??

Best regards
Oliver

**Comment by hanleilei** [comment]
I'm using atom/VSCode, but these editors cannot provide more detail information to me, and typora displayed parsed error either..

**Comment by walkccc** [comment]
Hi @hanleilei,

This embedded LaTeX source code is designed to render correctly on the web, so there will be some discrepancies with the standard LaTeX.
