### ISSUE TITLE
15.3-2 Merge-Sort with DP

### ISSUE THREAD

**Issue by artkpv** [walkccc/CLRS#122]
Hi, thanks for this repository and ability to discuss the problems from CLRS!

For 15.3-2, don't you think that problems can actually overlap as they can repeat. Here is the example.
```
4 3 2 1 4 3 2 1 4 3 2 1 4 3 2 1
4 3 2 1 4 3 2 1 ...
4 3 2 1  4 3 2 1 ...
4 3  2 1  4 3 2 1 ...
3 4  1 2  4 3 2 1 ...
1 2 3 4  4 3 2 1 (memoization) ... 
1 2 3 4  1 2 3 4 ...
1 1 2 2 3 3 4 4  4 3 2 1 4 3 2 1 (memoization)
1 1 2 2 3 3 4 4  1 1 2 2 3 3 4 4
1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 

```
Of course there is problem with memoization. How to store solutions to previously solved? How to compute hash? Key storage: O(n), value: O(n). Compute hash time: O(n). It needs to iterate subproblem elements before solving it recursively to determine that the same problem solved before. Hence: $T(n) = 2T(n/2) + n + n$. Space: $~nlog(n)$.

**Comment by walkccc** [comment]
You just point out the problem, so that the sub-problems still do not overlap. This doesn't lead to a more efficient algorithm.

**Comment by artkpv** [comment]
@walkccc 
Actually sub-problems can overlap for some cases and it can lead to more efficient Merge-Sort (of course in general if we know that beforehand we can use counting sort or other). Consider the example above. In that case the Merge-Sort runs linearly but takes BigTheta(N) additional space for storage.

```
The example:
4 3 2 1 4 3 2 1 and repeats. Merge-Sort will sort only left sides then: 
................................ ................................
................ ................
........ ........
.... ....
.. ..

Or
...
256
128
64
32
16
8
4
2

Time:
Reduces to T(n) = T(n/2) + 3*n/2. Solve recursively left side, use memoization for right.
Master theorem:
    n^(log(b,a)+E), E>0, a*f(n/b)<=c*f(n), c<1
    1) 3n/2 = big omega(n^(0+1))
    2) (3*n/4 <= c*3n/2), let c=1/2 then 3n/4 <= 3n/4
    hence
    T(n) = Big Theta (n). It takes linear time.
```

So in general, yes, Merge-Sort is not good candidate for dynamic programming but there are exceptions.

**Comment by CurieLuo** [comment]
But the average performance will only be worse using memorization in merge sort.

**Comment by walkccc** [comment]
@artkpv,
You are right, but this question is obviously not suitable. Anyway, I appreciate your suggestion!

**Comment by walkccc** [comment]
@artkpv
You are right, but this question is obviously not suitable. Anyway, I appreciate your suggestion!
