### ISSUE TITLE
Exercice 31.1-8

### ISSUE THREAD

**Issue by NicolasRoelandt** [walkccc/CLRS#13]
[For 31.1-8](https://github.com/walkccc/CLRS/blob/master/docs/Chap31/31.1.md#311-8), it is written "Iterate a from 2 to sqrt(n), and do binary searching." But if n contains B bits, sqrt(n) contains about B/2 bits, and it contains 2^(B/2) values, which is not polynomial but exponential in term of B.

**Comment by walkccc** [comment]
Hey, thank you for your knowledge. I've updated the answer and please check my website [31.1-8](https://walkccc.github.io/CLRS/Chap31/31.1/#311-8). The math equations are only rendered here!

**Comment by NicolasRoelandt** [comment]
Thank you, just to make sure because it's not really clear : you do a binary search on k and for each k you do a binary search on a ?
