### ISSUE TITLE
Problem with 3.2-3

### ISSUE THREAD

**Issue by MarkChenYutian** [walkccc/CLRS#131]
I think the solution of 3.2-3 is not totally correct on the prove of n!=o(n^n) and n!=ω(2^n)
The given solution is only proving that n!=O(n^n) and n!=Ω(2^n).
The solution should use the magnitude of (n!/n^n) as n->∞ and (n!/2^n) as n-> ∞ to prove it.

**Comment by walkccc** [comment]
Sorry for the late reply, I've updated the solution [here](https://walkccc.github.io/CLRS/Chap03/3.2/#32-3), please check it. Thanks!
