### ISSUE TITLE
2.3-7 Suggestion

### ISSUE THREAD

**Issue by MrMaester** [walkccc/CLRS#132]
3. Sort the elements in S'.

Every element z in S' is z = x - y, for each element y in S.

Since S has been sorted in step 1, it contains all the elements in increasing order. So, won't S' contain all the elements in a decreasing order, which is to suggest that S' is already sorted (decreasing order).
If this is true, this step would be redundant, although it wouldn't affect the asymptotic complexity in case one uses an algorithm with logarithmic time complexity to sort this set.

**Comment by walkccc** [comment]
Hi @MrMaester,
thanks for your contribution first.
Could you describe this more clearly so that I can quote your solution.

**Comment by walkccc** [comment]
Hi @MrMaester,
I've updated the solution [here](https://walkccc.github.io/CLRS/Chap02/2.3/#23-7-star). Sorry for the late update.
