### ISSUE TITLE
27.2-5 Solution (suggestion)

### ISSUE THREAD

**Issue by Amila-Rukshan** [walkccc/CLRS#135]
I think four n/2*n/2 sub matrices(A11, A12, A21, A22) can be transposed recursively and then exchange A21 with A12 in place. (Assuming n is a power of 2)

```
P_Matrix_Transpose(A)
     n = A.rows
     if n == 1
          return 
     else partiton A into n/2*n/2 sub matrices as A11, A12, A21, A22
            spawn P_Matrix_Transpose(A11)
            spawn P_Matrix_Transpose(A12)
            spawn P_Matrix_Transpose(A21)
            P_Matrix_Transpose(A22)
            sync
            // exchanging A21 with A12
            parallel for i = 1 to n/2
                  parallel for j = 1+n/2 to n
                         a[i, j] <-> a[i + n/2, j - n/2]
```
span T(n) = T(n/2) + O(lg n) = O(lg n * lg n)
work T(n) = 4T(n/2) + O(n^2) = O(n^2 * lg n)

**Comment by walkccc** [comment]
Hi @Amila-Rukshan,
thanks for providing the solution.
I'll review this when I am free!

**Comment by walkccc** [comment]
Sorry for the late reply, I've updated the solution [here](https://walkccc.github.io/CLRS/Chap27/27.2/#272-5), please check it. Thank you!
