### ISSUE TITLE
Solution of 26.1-6 and 26.1-7 is missing

### ISSUE THREAD

**Issue by GaurangTandon** [walkccc/CLRS#136]
Hello, the [website](https://walkccc.github.io/CLRS/Chap26/26.1/) currently says _(Removed)_ . I really wanted that solution though :( I notice you have said under "Annoucements" on the README that we can use the copyrighted solution if credit is given. 

Can we do that then? Or, if you're busy, would you want me to google up the question and put together a simple solution and submit a PR?  I googled and found solutions [here](http://sites.math.rutgers.edu/~ajl213/CLRS/Ch26.pdf) and [here](https://github.com/gzc/CLRS/blob/master/C26-Flow-networks/26.1.md), though not sure if they are protected by copyright or something.

**Comment by walkccc** [comment]
If there's no copyright issue regarding the solution. You can definitely help me finish this work!
