### ISSUE TITLE
6.5-8 the second solution is not absolutely wrong

### ISSUE THREAD

**Issue by leewwe** [walkccc/CLRS#140]
In the exercise 6.5-8, the second solution is not absolutely wrong.
if you exchange line 3 and 4, it is correct.

Like the follow
```
1. HEAP-DELETE(A, i)
2.     A[i] = A[A.heap-size]
3.     A.heap-size = A.heap-size - 1
4.     MAX-HEAPIFY(A, i)
```

**Comment by walkccc** [comment]
Thank you! I've updated [here](https://walkccc.github.io/CLRS/Chap06/6.5/#65-8).
