### ISSUE TITLE
18.1-3(minimum degree is 2 not 3)

### ISSUE THREAD

**Issue by liuzengh** [walkccc/CLRS#146]
minimum degree t = 2, We know that every node except the root must have at least **t - 1 = 1** keys, and at most **2t - 1 = 3** keys

**Comment by walkccc** [comment]
Sorry for the late reply. I've updated the solution [here](https://walkccc.github.io/CLRS/Chap18/18.1/#181-3). Please check it. Thanks!

**Comment by liuzengh** [comment]
Show all legal B-trees of minimum degree 22 that represent \{1, 2, 3, 4, 5\}{1,2,3,4,5}.
--------------------------------------------------------------------------------------------------------------------------------------------------
The simplest B-tree occurs when the minimum degre t = 2. Every internal node then has either 2,
3, or 4 children, and we have a 2-3-4 tree.&nbsp; your&nbsp; missed&nbsp; some correct&nbsp; solutions.&nbsp; for example, below tree:
&nbsp; &nbsp; &nbsp; &nbsp; |4|&nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; ----&nbsp; &nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; /&nbsp; &nbsp; \&nbsp; &nbsp;
----------&nbsp; &nbsp; &nbsp;----
&nbsp;|1 2 3|&nbsp; &nbsp; |5|
----------&nbsp; &nbsp; &nbsp;----





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jay Chen"<notifications@github.com&gt;; 
发送时间: 2019年9月26日(星期四) 凌晨2:37
收件人: "walkccc/CLRS"<CLRS@noreply.github.com&gt;; 
抄送: "329047820"<329047820@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [walkccc/CLRS] 18.1-3(minimum degree is 2 not 3) (#146)




Sorry for the late reply. I've updated the solution here. Please check it. Thanks!

**Comment by niloct** [comment]
Is this another solution to the problem ?

```
   |2 4| 
  /  |  \
|1| |3| |5|
```
