### ISSUE TITLE
Ch31 problem 3 complexities

### ISSUE THREAD

**Issue by NicolasRoelandt** [walkccc/CLRS#15]
In [ch31 problem 3](https://github.com/walkccc/CLRS/blob/master/docs/Chap31/Problems/31-3.md), the second complexity is not correct. I'm pretty sure that it should be O(B 2^B), since we do n = 2^B additions of size B = lg n.
If you compute sum_(i=1)^n lg n, it's O(n lg n ) by the integral approximation.
Another way to see it, the recurrence is T(n) = T(n-1) + lg n , which is the same than problem [4.3.h](https://walkccc.github.io/CLRS/Chap04/Problems/4-3/).

However for the first one, I'm not really sure how you could compute it, the recurrence can be upper bounded by the recurrence T(n) = 2 T(n-1) + lg n and I don't know how to compute it.
If you try to compute the sum, it's 
sum_(i=0)^(n-1) 2^(n-i) lg i  
I don't know how to compute or bound that sum either.

**Comment by walkccc** [comment]
Thanks for your reply. I've updated the answer [here](https://walkccc.github.io/CLRS/Chap31/Problems/31-3/). Please check.
