### ISSUE TITLE
Solution to Problem 8-2.e that works for records (rewritten in pseudocode)

### ISSUE THREAD

**Issue by Gutdub** [walkccc/CLRS#150]
I don't think the current solution works for records. The current solution basically create some numbers according to the keys of records in the input array, and then it throws away all the records and keep those numbers. This certainly works for an array of numbers, but not for n records.

I came up with this solution that does the problem in the right manner after some hours of thinking and coding. Here's some pseudocode.

`

    ALTERNATE-COUNTING-SORT(array, k):
    """
    diff: in place (storage space is theta(k)) but not stable
    """
    c = [0 for i = 1 to k]
    for i = 1 to array.length:
        c[array[i]] = c[array[i]] + 1
    for j = 2 to k:
        c[j] = c[j] + c[j - 1]
    insert sentinel element NIL at the start of array (anything works)
    b = a copy of c, excluding the last element of c
    insert number 1 at the start of b
    # b now contains the "endpoints" for c
    for i = 2 to array.length:
        while c[array[i]] != b[array[i]]:
            key = array[i]
            swap array[c[array[i]]] with array[i]
            while array[c[key]] == key:  # make sure that elements with the same keys will not be swapped
                c[key] = c[key] - 1
    remove the sentinel element
    return array

The thing is coded, but I don't know how to type it into the md file. Can anyone help?

**Comment by sukhesai** [comment]
Ain't the following Pseudo code better(if not , address the issue with this):
```
COUNTING-SORT(A,k):
    n = A.length
    c = [0 for i = 1 to k]
    for i = 1 to n
        c[A[i]] = c[A[i]] + 1
    p = 0           // p is the position of element in A which is updated
    for i = 1 to k
        for j = 1 to c[i]     // if c[i] == 0 , then this loop does not run
            A[p] = i
            p = p + 1
    return A
```
