### ISSUE TITLE
the Exercises 13.4-4

### ISSUE THREAD

**Issue by leewwe** [walkccc/CLRS#151]
There must be something wrong in this answer.
The w is impossible to be T.nil, because the book's original content is as follow:

> Since node x is doubly black, node w cannot be T.nil, because otherwise, the number of blacks on the simple path from x.p to the (singly black) leaf w would be smaller than the number on the simple path from x.p to x.

**Comment by walkccc** [comment]
Sorry for the late reply. I've updated the solution [here](https://walkccc.github.io/CLRS/Chap13/13.4/#134-4). Please check it. Thanks!
