### ISSUE TITLE
11.2-3

### ISSUE THREAD

**Issue by chperich** [walkccc/CLRS#217]
For the question: Professor Marley hypothesizes that he can obtain substantial performance gains by modifying the chaining scheme to keep each list in sorted order. How does the professor's modification affect the running time for successful searches, unsuccessful searches, insertions, and deletions?

Given that the collision list is in sorted order, the look up can be done in O(log n) where n is the length of the collision list. Hence the right answer should be:

Successful searches:  Θ(1+ log α).
Unsuccessful searches: Θ(1+log α).
Insertions: same as successful searches Θ(1+log α).
Deletions:  Θ(1).

**Comment by walkccc** [comment]
Thank you. I've updated it [here](https://walkccc.github.io/CLRS/Chap11/11.2/#112-3).
