### ISSUE TITLE
[Exercise 15.2-4] 

### ISSUE THREAD

**Issue by FlintNT** [walkccc/CLRS#222]
Thanks for all the solutions! It helps me a lot!
However, I think the formula in the solution of Ex15.2-4 can be more accurate. You can add the condition `i < j` under the sum symbol to make it more clear.

**Comment by walkccc** [comment]
Thank you. It must be typos. I've changed `j = 1` to `j = i` [here](https://walkccc.github.io/CLRS/Chap15/15.2/#152-4).
