### ISSUE TITLE
the van Emde Boas 20.2-2 have problem

### ISSUE THREAD

**Issue by leewwe** [walkccc/CLRS#224]
the code of No.8 line have problem.
in the line 7, the i's range is [0, sqrt(u) - 1], which is the 2 levels construction's solution.
To calculate the right cluster[high(x)]'s index, the line 8 should be "if PROTO-vEB-MEMBER(V.cluster[x.high], low(i))", which can do the right thing.
```

1. PROTO-vEB-DELETE(V, x)
2.     if V.u == 2
3.         V.A[x] = 0
4.     else
5.         PROTO-vEB-DELETE(V.cluster[x.high], x.low)
6.         inCluster = false
7.         for i = 0 to sqrt(u) - 1
**8.             if PROTO-vEB-MEMBER(V.cluster[x.high], low(i))**
9.                 inCluster = true
10.                 break
11.         if inCluster == false
12.             PROTO-vEB-DELETE(V.summary, x.high)
```

**Comment by walkccc** [comment]
Thank you. I've updated it [here](https://walkccc.github.io/CLRS/Chap20/20.2/#202-2).
