### ISSUE TITLE
How to run the website project ?

### ISSUE THREAD

**Issue by FruitTea2015** [walkccc/CLRS#225]
Excuse me , I'm a new comer to the CS and software project . 
I wonder HOW CAN I RUN THIS PROJECT ON MY SERVER OR PC ?

**Comment by walkccc** [comment]
Hi @FruitTea2015, make sure you have installed [MkDocs](https://www.mkdocs.org/#installation) and [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/) in your computer.
Then, you could run `mkdocs serve` in your command line interface to run the website in your localhost.
