### ISSUE TITLE
Problem 5.2-2: Wrong assumption leading to wrong answer.

### ISSUE THREAD

**Issue by toan-n-phan** [walkccc/CLRS#252]
The second sentence of the solution states that:

> Since we view the candidate ranking as reading an random permutation, this is equivalent to the probability that a random permutation is a decreasing sequence followed by an increase, followed by another decreasing sequence.

The assumption is that the hiring sequence must be able to partition into 2 parts, both in decreasing order. However, this is incorrect: the second sequence doesn't need to be decreasing, only need to have the biggest value at the beginning.

Example: [3 2 1] [6 4 5] is also a valid hiring sequence with only the first part in decreasing order.

**Comment by walkccc** [comment]
This issue has been fixed in #262. Thank you!
https://walkccc.github.io/CLRS/Chap05/5.2/#52-2
