### ISSUE TITLE
Problem 5.1-2

### ISSUE THREAD

**Issue by tkbartel** [walkccc/CLRS#253]
The given algorithm does not return a random number between a and b. For example, RANDOM(0,2) will return 1 twice as often as it returns 0.

**Comment by run27017** [comment]
The solution of Execise 5.1-3 is very nice, but 5.1-2 is not as nice as 5.1-3. Firstly, the running time is determinate， not expected. Secondly, it should also use the same strategy as 5.1-3, which running twice again until it generates a valid value. 

> https://github.com/gzc/CLRS/blob/master/C05-Probabilistic-Analysis-and-Randomized-Algorithms/5.1.md
