### ISSUE TITLE
Longest-Path-Bottom-Up

### ISSUE THREAD

**Issue by whoodes** [walkccc/CLRS#28]
Hello, on your work corresponding to chapter 15 problems, 15-1.  Longest-Path-2, using a bottom up approach.  I am wondering if there is a typo in the conditional of the nested for each loop...

1    if dist[u] + w(u, v) > dist[v]
2                next[v] = dist[u] + w(u, v)
3                next[u] = v

It seems to be that line 2 should be dist[v] = dist[u] + w(u, v) ...Would you agree?

**Comment by walkccc** [comment]
You're right, thanks!
