### ISSUE TITLE
Is it possible to make it a pdf file?

### ISSUE THREAD

**Issue by maplewizard** [walkccc/CLRS#3]
Hi, I have read your site and find it very helpful. I just want to print it out on paper to make it easier to read. I wonder could you please provide a pdf version and I can use. A possible way is to put your site on gitbook which can generate pdf file automatically.

**Comment by walkccc** [comment]
All of my .md files are available, you can try to host it by yourself. Alternatively, you can also generate the .pdf file by something like Pandoc, Kramed.
