### ISSUE TITLE
possible problem in 25.2-7

### ISSUE THREAD

**Issue by quq99** [walkccc/CLRS#37]
![image](https://user-images.githubusercontent.com/16220371/48675444-f2d30380-eb26-11e8-93fc-1a1669bf2442.png)

Would it be 
![image](https://user-images.githubusercontent.com/16220371/48675478-3b8abc80-eb27-11e8-9e5a-25b9c1a3a897.png)

**Comment by walkccc** [comment]
Yes, thanks.
