### ISSUE TITLE
Is 4-3a incorrect?

### ISSUE THREAD

**Issue by prkumar** [walkccc/CLRS#43]
First off, thanks for this great resource!

I see that [the answer for 4-3a](https://walkccc.github.io/CLRS/Chap04/Problems/4-3/) is derived using the master theorem. However, to me, this recurrence seems to fall outside the scope of the master theorem: specifically, the textbook notes that "there is a gap between cases 1 and 2 [of the master theorem] when f(n) is smaller than n^(log_b(a)), but not polynomially smaller" (Page 95). Wouldn't this problem fall into that gap?  

For an example of another recurrence that falls into a similar gap between cases 2 and 3, checkout the example given at the bottom of that same page (Page 95): T(n) = 2T(n/2) + nlgn.

**Comment by walkccc** [comment]
I've checked the answer and I think that there's no problem in 4-3 (a). Anyway, feel free to reopen the issue 👍.
