### ISSUE TITLE
Does "P.M.I." mean Principle of Mathematical Induction?

### ISSUE THREAD

**Issue by liyi93319** [walkccc/CLRS#449]
https://github.com/walkccc/CLRS/blob/89279c098f75a5146aa1925c7887a695d9115ba4/docs/Chap02/2.3.md

The answer to Exercise 2.3-3 says "By P.M.I., $T(n) = n\lg nT(n)=nlgn$, when n is an exact power of 22. "

Does "P.M.I." there mean Principle of Mathematical Induction?

**Comment by LeverImmy** [comment]
It should be.

**Comment by walkccc** [comment]
Yes.
