### ISSUE TITLE
Markdown render error - problems 1-1, 3-2, 3-6

### ISSUE THREAD

**Issue by PaiZuZe** [walkccc/CLRS#478]
There seems to be some problem with the markdown of these pages [1-1.md](https://github.com/walkccc/CLRS/blob/main/docs/Chap01/Problems/1-1.md), [3-2.md](https://github.com/walkccc/CLRS/blob/main/docs/Chap03/Problems/3-2.md) and [3-6.md](https://github.com/walkccc/CLRS/blob/main/docs/Chap03/Problems/3-6.md).

This render problem appears on both Firefox and Chromium, though on vscode markdown preview it renders with no problem.

![Screenshot_20230427_120451](https://user-images.githubusercontent.com/21297506/234905069-6cd80b4e-e1a9-466c-acd4-226b629f69d9.png)

The issue seems to happen every time a double line space (\\\\\\\\) is followed by a \hline.

Replacing the \\\\\\\\ for \newline\newline seems to fix the error as can be seen [here](https://github.com/PaiZuZe/CLRS/blob/bugfix/hline/docs/Chap01/Problems/1-1.md).

Removing one of the line breaks also seems to work as showed in [this](https://github.com/walkccc/CLRS/pull/476) PR by @Umesh-Kumar-01.

**Comment by walkccc** [comment]
Hi @PaiZuZe,

Initially, GitHub does not support TeX. Therefore, those math equations are not correctly rendered because they are written to be rendered for Mkdocs. Could you please redirect to this [built page](https://walkccc.me/CLRS/Chap01/Problems/1-1/) to see if it works for you?

**Comment by PaiZuZe** [comment]
No errors message on the site.

![Screenshot_20230512_112454](https://github.com/walkccc/CLRS/assets/21297506/6932e7f7-89dc-4b01-ae50-e740d962034f)

If you compare the render of the website with my fix [here](https://github.com/PaiZuZe/CLRS/blob/bugfix/hline/docs/Chap01/Problems/1-1.md) , It seems like only one line break is begin rendered.

If the intended way of seeing the pages is through the https://walkccc.me and not the GitHub repo I guess there is no problem to fix. Feel free to close the issue
