### ISSUE TITLE
What is meant by omit! in answers?

### ISSUE THREAD

**Issue by jxu** [walkccc/CLRS#515]
I can contribute some solutions to the computational geometry chapter. Should omitted answers be filled in for completeness?

**Comment by jxu** [comment]
Same for (Removed) @walkccc

**Comment by walkccc** [comment]
Hi. Please create a PR if you'd like to contribute. Thanks!

**Comment by jxu** [comment]
So these should be filled in? or not

**Comment by walkccc** [comment]
Feel free to fill them in.
