### ISSUE TITLE
22.4-2 should consider overlapping subproblem

### ISSUE THREAD

**Issue by matonglidewazi** [walkccc/CLRS#58]
Hi thanks for the contribution !

I found an issue in 22.4-2:

![default](https://user-images.githubusercontent.com/22267548/50045267-b16a4100-005d-11e9-9865-c6f3eafa7021.PNG)

The recursive solution works but does not end in linear time. The subproblem is overlapping. Take the path from s to t as example, we mush do a topo sort first, take the intermediate node {v1....vk-1}, and run a buttom-up DP from t. call s v_{0}, t v_{k}, we have: 

```cpp
SIMPLE-PATHS(G, u, v)
    Topo-Sort(G)
    list the vertex between u, v as {v[1], v[2], ...., v[k-1]}
    let v[0] = u, v[k] = v
    for j = 0 to k-1
        DP[j] = INT_MAX
    DP[k] = 1
    
    return SIMPLE-PATHS-AID(G, DP, 0)
    
 SIMPLE-PATHS-AID(G, DP, i)
    if i > k
        Return 0
    else if DP[i] != INT_MAX
        Return DP[i]
    else 
       DP[i] = 0
       for v[m] in G.adjlist(v[i]) and 0 < m <= k
            DP[i] += SIMPLE-PATHS-AID(G, DP, m)
       Return DP[i]   
```

And return DP[0] as answer. In this way we avoid recursively solve overlapping problem and return answer in $\Theta(V+E)$.

**Comment by matonglidewazi** [comment]
See pull request #59

**Comment by walkccc** [comment]
Thank you very much!
