### ISSUE TITLE
16.1-5 has better solution than N^3

### ISSUE THREAD

**Issue by zed-b** [walkccc/CLRS#78]
Sort all intervals by beginning time - O(n*log(n))
Have a DP[N] which shows the best value calculated for intervals up to that interval including it (left to right), initially DP[i] = value[i]
For each interval i, check each interval k = 0->i-1 and if they don't overlap with i, DP[i] = max(DP[i],value[i]+DP[k]), result is max element of DP, which turns out to be O(N^2)

**Comment by walkccc** [comment]
Thanks for the commenting first. I think sorting doesn't make it run faster and DP still requires O(n^3). I'll temporarily close the issue. Feel free to reopen it!

Thank you!

**Comment by zed-b** [comment]
Sorting is just the beginning of my algorithm, but it's ok if you don't follow my thought. Have a nice day.
