### ISSUE TITLE
4.4-3 is incorrect

### ISSUE THREAD

**Issue by StoneT2000** [walkccc/CLRS#81]
In question 4.4-3, originally it was written that we guess T(n) ≤ cn^2 - 6n
However, if we T(n) = 4T(n/2 + 2) + n, we get that
T(n) ≤ 4(c(n/2 + 2)^2 - 6(n/2 + 2) + n = cn^2 + 8cn + 16 - 12n - 48 + n
It was falsely written that the above = cn^2 - 4cn -32c + n

I submitted a PR that addresses this and provides a more general solution by guessing T(n) ≤ cn^2 - dn, for d ≥ 0.

**Comment by walkccc** [comment]
Thank you, and I've updated the solution [here](https://walkccc.github.io/CLRS/Chap04/4.4/#44-3). Please check it.

**Comment by StoneT2000** [comment]
Looks good
