### ISSUE TITLE
2.3.7 has better solution

### ISSUE THREAD

**Issue by JackXuXin** [walkccc/CLRS#84]
`function divide( array, flag )
	let bigger, equal, smaller be a empty array
	for i=1,array.length do
		if array[i] > flag then 
			insert(bigger, array[i])
		elseif array[i] < flag 
			insert(smaller, array[i])
		else 
			insert(equal, array[i])
		end
	end

	return bigger, equal, smaller
end

function find_sum_aux( smaller, bigger, flag, target )
	if smaller.length == 1 and bigger.length == 1 then
		return true
	elseif smaller.length == 0 or bigger.length == 0 then
		return false
	else
		bigger1, equal1, smaller1 = divide(smaller, target/2 - flag - flag/2)
		bigger2, equal2, smaller2 = divide(bigger, target/2 + flag + flag/2)
		if equal1.length > 0 and equal2.length > 0 then
			return true 
		else
			return find_sum_aux(bigger1, smaller2, 3*flag/4, target) or find_sum_aux(smaller1, bigger2, 1*flag/4, target)
		end
	end
end

function find_sum( array, target )
	bigger, equal, smaller = divide(array, target/2)
	if equal.length >= 2 then
		return true
	else
		return find_sum_aux(smaller, bigger, target/2, target)
	end
end
`
loop invariant:
init:
if there is two number whose sum is x, the smaller one must  small the target/2 and the bigger one should bigger the target/2.
maintance:
there are two array, smaller one should in smaller array, and bigger one in bigger array,continue divde to more smaller and more bigger one.
end:
if one of two array is zero means no sum. two of array are length 1 means has

**Comment by walkccc** [comment]
Could you please format the code better and fix the grammar errors?
It's hard for me to understand what you want to express.

Feel free to reopen the issue if you like.
Thank you.
