### ISSUE TITLE
Dark theme website with monokai code highlighting?

### ISSUE THREAD

**Issue by GaurangTandon** [walkccc/CLRS#85]
Can something be done about this feature requests? I don't think it should be too hard to implement it. You can implement a switch similar to how it has been done on the [CS APP 3e solutions](https://dreamanddead.gitbooks.io/csapp-3e-solutions) website.

**Comment by walkccc** [comment]
The link you provide is a service from the legacy of GitBook team. You can clone my repo and build one if you like.
