### ISSUE TITLE
32.1-4 solution is missing

### ISSUE THREAD

**Issue by Silver-Snitch** [walkccc/CLRS#86]
Only the running time is mentioned.
The solution (most probably correct) can be found in my git repo CP Library in the string.cpp file

**Comment by walkccc** [comment]
After testing your code below (I've formatted it better):

```cpp
#include <bits/stdc++.h>
using namespace std;

bool occurence(string a, string b, int pa = 0, int pb = 0) {
    if (pb == b.length()) return true;
    if (pa == a.length()) return false;
    if (b[pb] == '!')
        return (occurence(a, b, pa, pb + 1) || occurence(a, b, pa + 1, pb));
    else if (a[pa] == b[pb])
        return occurence(a, b, pa + 1, pb + 1);
    else
        return false;
}

int main() {
    string p, t;
    cin >> t >> p;

    if (occurence(t, p)) cout << "Yes";

    return 0;   
}
```

with

```bash
./a.out
cabccbacbacab
ab!ba!c
```

It printed nothing, and could you please check it?

**Comment by buscasangre** [comment]
@walkccc  I would like to suggest a change in occurence function , you can test this code 
`#include <bits/stdc++.h>`
`using namespace std;`

`bool occurence(string a, string b, int pa = 0, int pb = 0) {`
 `   if (pb == b.length()) return true;`
  `  if (pa == a.length()) return false;`
   ` if (b[pb] == '!')`
    `    return (occurence(a, b, pa, pb + 1) || occurence(a, b, pa + 1, pb));`
    `else if (a[pa] == b[pb])`
     `   return occurence(a, b, pa + 1, pb + 1);`
  // added this line 
   ` else return occurence(a,b,pa+1,pb);`
`}`

`int main() `
`{`
   ` string p, t;`
   `cin >> t >> p;`
   ` if (occurence(t, p)) cout << "Yes\n";`
    `else cout<<"No\n";`
    `return 0;`   
`}`

**Comment by Silver-Snitch** [comment]
There was a slight mistake
`bool occurance(string a,string b,int pa=0,int pb=0)`
`{`
`	if(pb==b.length()) return true;`   
`	if(pa==a.length()) return false;`  
`	if(b[pb]=='!')`                             
`		return (occurance(a,b,pa,pb+1)||occurance(a,b,pa+1,pb));`
`	else if(a[pa]==b[pb])`                
`		return occurance(a,b,pa+1,pb+1);`
`	else if(pb==0)`           
`		return occurance(a,b,pa+1,pb);`
`	else`
`		return false;`
`}`

Worked fine for the cases I tried
Cheers!

**Comment by walkccc** [comment]
This works, thanks a lot.
I've updated the solution [here](https://walkccc.github.io/CLRS/Chap32/32.1/#321-4).
Please check.

**Comment by wstcliyu** [comment]
I do not get why you think this solution works fine. My testcase is a = "ab!c" and b = "aabdc". It should output true but this program outputs false.

**Comment by walkccc** [comment]
@wstcliyu `a` should be "aabdc" instead of "ab!c" and `b` should be "ab!c"  instead of "aabdc".

**Comment by franklinchou** [comment]
Confirmed that this solution does not work for @wstcliyu's test case.

**Comment by franklinchou** [comment]
I believe @wstcliyu's case is actually expected bevhaiour. Chapter 32 of CLRS handles greedy algorithms. Isn't this an approach where a greedy algorithm wouldn't suffice?

**Comment by wstcliyu** [comment]
I think the algorithm should be fairly intuitive. Assume the pattern is like P = "p1!p2!...!pk", then we should look for the first occurence of p1 in text T, followed by the first occurence of p2, p3, ..., pk. If the pattern P is of length m and the text T is of length n then the runtime should be O(mn).

**Comment by walkccc** [comment]
@wstcliyu
given:
```
P = "ab*ba*c"
T = "cabccbcabacab"
```

There's a problem by using ur intuitive algorithm.
Let me align the strings a bit:

```
P =  "ab* ba*c"
T = "cabccbcabacab"
           ↑
```

The characters of P and T where ↑ points is not equal. Therefore, if we linearly scan these two strings, it'll output `false`.

However, it should output`true` since the following match. (* can be zero length)

```
P =  "ab*    bac"
T = "cabccbcabacab"
```

**Comment by wstcliyu** [comment]
> @wstcliyu
> 
> First of all, thank you for pointing out the problem.
> 
> given:
> 
> ```
> P = "ab*ba*c"
> T = "cabccbcabacab"
> ```
> There's a problem by using ur intuitive algorithm.
> Let me align the strings a bit:
> 
> ```
> P =  "ab* ba*c"
> T = "cabccbcabacab"
>            ↑
> ```
> The characters of P and T where ↑ points is not equal. Therefore, if we linearly scan these two strings, it'll output `false`.
> 
> However, it should output`true` since the following match. (* can be zero length)
> 
> ```
> P =  "ab*    bac"
> T = "cabccbcabacab"
> ```
P =  "ab* ba*c"
T = "cabccbcabacab"
           ↑


> @wstcliyu
> 
> First of all, thank you for pointing out the problem.
> 
> Given:
> 
> ```
> P = "ab*ba*c"
> T = "cabccbcabacab"
> ```
> There's a problem by using ur intuitive algorithm.
> Let me align the strings a bit:
> 
> ```
> P =  "ab* ba*c"
> T = "cabccbcabacab"
>            ↑
> ```
> The characters of P and T where ↑ points is not equal. Therefore, if we linearly scan these two strings, it'll output `false`.
> 
> However, it should output`true` since the following match. (* can be zero length)
> 
> ```
> P =  "ab*    bac"
> T = "cabccbcabacab"
> ```

I do not know why you stop matching and return false when you trying to match "ba" with "bc". What you need to do is naive string match, increasing your shift and matching from 'b' again.

**Comment by buscasangre** [comment]
> I do not get why you think this solution works fine. My testcase is a = "ab!c" and b = "aabdc". It should output true but this program outputs false.

@wstcliyu  a is the text and b is pattern string here , and it is assumed in the question that only Patten string will contain !(special character).

**Comment by buscasangre** [comment]
> There was a slight mistake
> 
> ```c++
> bool occurance(string a, string b, int pa = 0, int pb = 0) {
>     if (pb == b.length()) return true;
>     if (pa == a.length()) return false;
>     if (b[pb] == '!')
>         return (occurance(a, b, pa, pb + 1) || occurance(a, b, pa + 1, pb));
>     else if (a[pa] == b[pb])
>         return occurance(a, b, pa + 1, pb + 1);
>     else if (pb == 0)
>         return occurance(a, b, pa + 1, pb);
>     else
>         return false;
> }
> ```
> 
> Worked fine for the cases I tried
> Cheers!
> 
> This is wrong due to the test case provided by @wstcliyu:
> 
> ```
> a = "aabdc"
> b = "ab!c"
> ```

@Silver-Snitch , I think my  code was already correct . Please check the input for which you are getting wrong answer and tell me. 

`bool occurance(string a, string b, int pa = 0, int pb = 0) {
    if (pb == b.length()) return true;
    if (pa == a.length()) return false;
    if (b[pb] == '!')
        return (occurance(a, b, pa, pb + 1) || occurance(a, b, pa + 1, pb));
    else if (a[pa] == b[pb])
        return occurance(a, b, pa + 1, pb + 1);
    // added this line 
    else return occurance(a, b, pa + 1, pb);
}`
use this function instead of yours.

**Comment by buscasangre** [comment]
> cabccbcabaca

> @walkccc I would like to suggest a change in occurance function , you can test this code
> 
> ```c++
> #include <bits/stdc++.h>
> using namespace std;
> 
> bool occurance(string a, string b, int pa = 0, int pb = 0) {
>     if (pb == b.length()) return true;
>     if (pa == a.length()) return false;
>     if (b[pb] == '!')
>         return (occurance(a, b, pa, pb + 1) || occurance(a, b, pa + 1, pb));
>     else if (a[pa] == b[pb])
>         return occurance(a, b, pa + 1, pb + 1);
>     // added this line 
>     else return occurance(a, b, pa + 1, pb);
> }
> 
> int main()  {
>     string p, t;
>     cin >> t >> p;
> 
>     if (occurance(t, p)) cout << "Yes\n";
>     else cout << "No\n";
> 
>     return 0;   
> }
> ```
> 
> Here **!** is the gap character.

@walkccc  Please check your input with this code and tell me if there are some issues .

Text = "cabccbcabacab"
Pattern = "ab!bac"
This code is printing **Yes** , which is the correct answer.

**Comment by walkccc** [comment]
@buscasangre 
It doesn't pass:

```
T = "cabccbcabacab"
P = "ab*ba*c"
```

Since the original variable is extremely confusion, I modify the code with:

```cpp
#include <bits/stdc++.h>
using namespace std;

bool occurance(string text, string pattern, int t = 0, int p = 0) {
    if (p == pattern.length()) return true;
    if (t == text.length()) return false;
    if (pattern[p] == '*')
        return (occurance(text, pattern, t, p + 1) ||
                occurance(text, pattern, t + 1, p));
    else if (text[t] == pattern[p])
        return occurance(text, pattern, t + 1, p + 1);
    else
        return occurance(text, pattern, t + 1, p);
}

int main() {
    string pattern, text;

    cout << "text: ";
    cin >> text;
    cout << "pattern: ";
    cin >> pattern;

    if (occurance(text, pattern))
        cout << "Yes\n";
    else
        cout << "No\n";

    return 0;
}
```

**Comment by walkccc** [comment]
@buscasangre 

It didn't pass the following cases which should output "No" instead of "Yes": 

```
T: "aabdc"
P: "ad" || "ac" || "bc"
```

Since the original variables is extremely confusion, I modified the code below.
Notice that I've changed `'!'` to `'*'` in order to stick to the conventional notation of regex.

```cpp
#include <bits/stdc++.h>
using namespace std;

bool occurance(string text, string pattern, int t = 0, int p = 0) {
    if (p == pattern.length()) return true;
    if (t == text.length()) return false;
    if (pattern[p] == '*')
        return (occurance(text, pattern, t, p + 1) ||
                occurance(text, pattern, t + 1, p));
    else if (text[t] == pattern[p])
        return occurance(text, pattern, t + 1, p + 1);
    else
        return occurance(text, pattern, t + 1, p);
}

int main() {
    string pattern, text;

    cout << "text: ";
    cin >> text;
    cout << "pattern: ";
    cin >> pattern;

    if (occurance(text, pattern))
        cout << "Yes\n";
    else
        cout << "No\n";

    return 0;
}
```

**Comment by ichn-hu** [comment]
Hi all, I've implemented the DP code below, feel free to test it with your own test example (it has passed all the tests in the discussion above).

```
#include <cstdio>
#include <cstring>

/*
Documentation

By using dynamic programming we could solve the problem in O(nm). We denote a binary two dimensional array $f_{ij}$ to be if we could match the first j characters of the pattern with the suffix of the first i characters of the text, therefore

\begin{align*}
f_{ij} =
\begin{case}
f_{i-1,j-1} or f_{i-1, j} or f_{i,j-1} \text{if P[j] is gap character} \\
f_{i-1,j-1} \text{if P[j] equals to T[i]}
\end{case}
\end{align*}

The running time is O(nm) because we could implement the algorithm in two layer of loop, see the code bellow.

*/

bool occur(char *T, char *P) {
    // we denote the gap character by '*', and we assume n, m < N
    const int N = 100;
    char gap = '*';
    int n = strlen(P), m = strlen(T);
    bool f[N][N];
    // f[i][j] means we've matched the first j characters of P with suffix of the first i characters of T
    memset(f, false, sizeof f);
    for (int i = 0; i <= m; ++i)
        f[i][0] = true; // matching 0 character, always true

    for (int i = 1; i <= m; ++i) {
        for (int j = 1; j <= n; ++j) {
            if (P[j - 1] == gap) {
                f[i][j] = f[i - 1][j - 1] | f[i - 1][j] | f[i][j - 1];
                // if current character in P is a gap character, then it could either
                // 1. match P[j - 1] and T[i - 1] (the first 2 cases)
                // 2. match P[j - 1] with nothing
            } else if (P[j - 1] == T[i - 1]) // otherwise matches if and only if the two characters are the same
                f[i][j] = f[i - 1][j - 1];
            if (j == n && f[i][j])
                return true;
        }
    }
    return false;
}

void test(char *T, char *P, bool has) {
    printf("Pattern: %s text: %s %s %s\n", P, T, has ? "occurs" : "not occurs", occur(T, P) == has ? "pass" : "fail");
}

int main() {
    test("abc", "a", true);
    test("abc", "c", true);
    test("abc", "*", true);
    test("abc", "*b*", true);
    test("abc", "*a", true);
    test("abc", "*a*b*c", true);
    test("abc", "*a*b*c*", true);
    test("cabccbacbacab", "ab*ba*c", true);
    test("cabccbacbacab", "ab*bca*c", false);
    test("cabccbacbacab", "ab*bac*c", true);
    test("aabdc", "ad", false);
    test("aabdc", "ac", false);
    test("aabdc", "bc", false);
    test("cabccbcabacab", "ab*bac", true);
}

```

@walkccc if you believe the code is correct I could update the docs by another pull request.

**Comment by walkccc** [comment]
Hey guys, I've updated the solution [here](https://walkccc.github.io/CLRS/Chap32/32.1/#321-4), please double check it. Thanks for your discussion.
