### ISSUE TITLE
12.3-5

### ISSUE THREAD

**Issue by zhenorzz** [walkccc/CLRS#9]
In the INSERT function, you may need to change the parent->successor when it's child larger than it (child.key > parent.key).

**Comment by zhenorzz** [comment]
2
           /    \
         1      4
2.successor = 4

when you insert 3:
             2
           /    \
         1      4
               /
             3
2.successor = 3

**Comment by walkccc** [comment]
I've updated it according to [this](https://blog.csdn.net/hrzr79011/article/details/41889431).
Have a look, thanks!
