### ISSUE TITLE
In problem 4-5 Chip testing, the solution doesn't apply if there are odd number of chips

### ISSUE THREAD

**Issue by EFanZh** [walkccc/CLRS#92]
If there are odd number of chips, one extra chip will be left out, if the extra chip is a good chip, the invariant might be broken in the grouped chip pairs.

There is a solution that fixes the problem: https://efanzh.org/2018/10/05/introduction-to-algorithms-exercises.html#chip-testing.

**Comment by walkccc** [comment]
I just updated [the solution](https://walkccc.github.io/CLRS/Chap04/Problems/4-5/).
Please check it.
Thank you.
