### ISSUE TITLE
There are some errors in Problem 3-3a

### ISSUE THREAD

**Issue by LouisChen0104** [walkccc/CLRS#96]
2^(2^n) and (n+1)! shouldn't be in the same equivalence class.
When n -> ∞, lg(2^(2^n) ) - lg((n+1)! ) = 2^n - lg((n+1)! ).
Since lg((n+1)!) = lg(n+1) + lg(n!) = Θ(lgn) + Θ(nlgn) = Θ(nlgn), there exists a constant c making lg((n+1)!) <= cnlgn. 
So when n ->∞,  2^n - lg((n+1)! ) >= 2^n - cnlgn >= 2^n - cn^2 -> ∞
Therefore, when n ->∞,  2^(2^n) / (n+1)! -> ∞, 2^(2^n) = ω((n+1)!).

**Comment by walkccc** [comment]
Thank you! I've fixed it [here](https://walkccc.github.io/CLRS/Chap03/Problems/3-3/).
