### ISSUE TITLE
17.4-2, when a_i-1 >= 1/2, a_i may be < 1/2

### ISSUE THREAD

**Issue by samolisov** [walkccc/CLRS#99]
In 17.4-2 we should consider a case when `a_i-1 == 1/2` (for example, we have a table of size 8 with only 4 elements). In this case, when we are dropping an element from the table, the load factor becomes bellow 1/2 (otherwise we is not able to reach 1/4 which is required for contraction, returning to the example, if we have deleted an element from the table there is only 3 elements and 3/8 < 1/2).

```latex
ĉ_i = c_i + Ф_i - Ф_i-1 = 1 + (1/2 * size_i-1 - num_i-1 + 1) - (2 * num_i-1 - size_i-1) = 2 + 3/2*size_i-1 - 3*num_i-1 = 2 + 3/2 * size_i-1 - 3/2 * size_i-1 = 2.
```

**Comment by buscasangre** [comment]
@samolisov  Yes you are totally right , there will be two cases in this scenario when (load factor) a_i-1 >=1/2 and the ith operation on a dynamic table is TABLE-DELETE.
Here , After performing TABLE-DELETE  load factor may or may not drop below 1/2 , but it is confirmed that load factor will always be greater than or equal to 1/4 , **except** when the size_i-1= 2 and num_i-1 =1(Here contraction will take place) Now finding the amortized cost.

Let  , 
**ĉ_i**  denotes the amortized cost with respect to **Ф_i** (potential )
**c_i** denotes the actual cost
**num_i** denotes the number of items stored in the table after ith operation
**size_i** denotes the total size of the table after the ith operation 
**a_i**  denotes the load factor 

**CASE-1**: When after deleting the element load factor is still greater than or equal to 1/2
Now ,
`` ĉ_i  =  c_i + Ф_i +Ф_i-1  =  1 + (2*num_i - size_i ) - (2*num_i-1 - size_i-1)``
As we know,
num_i = num_i-1 - 1
size_i = size_i-1
we can substitute them above
``ĉ_i = 1  + (2 * num_i - size_ i ) - (2 * (num_i + 1) - size_ i ) ``
On solving we get `` ĉ_i = -1``

**CASE-2** : When after deleting the element load factor becomes less than 1/2
Now, 
`` ĉ_i  =  c_i + Ф_i +Ф_i-1  =  1 + ( 1/2 * size_i  - num_i ) - (2*num_i-1 - size_i-1)``
As we know,
num_i = num_i-1 - 1
size_i = size_i-1
2 * num_i-1 = size_i-1
we can substitute them above
`` ĉ_i  =  c_i + Ф_i +Ф_i-1  =  1 + ( 1/2 * size_i  - num_i ) - (2*(num_i + 1) - size_i )``
On solving we get ``ĉ_i = 2``
